name: On-push workflow

on: push

jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dagger-function: ["test-fmt"]
        #dagger-function: ["test-fmt", "test-lint", "test-types", "test-unit"]
    steps:
      - uses: actions/checkout@v5
      - name: Call dagger function '${{ matrix.dagger-function }}'
        uses: .dagger
        with:
          module: https://github.com/grnc-learning-bytes/easy-crud-api/.dagger
          call: ${{ matrix.dagger-function }}
          version: "latest"  # semver vX.Y.Z
